#+title: Continuidad y límites
#+author: 
#+date: 2015-01-26 9:00

#+setupfile: opciones.org

#+beamer: \setbeamertemplate{navigation symbols}{}
#+beamer: \setbeamertemplate{items}[circle]
#+beamer: \languagepath{spanish}

#+latex_header: \usepackage{tikz}
#+latex_header: \usepackage{tikz-cd}
#+latex_header: \usepackage{pgfplots}
#+latex_header: \usetikzlibrary{babel}

#+beamer: \tableofcontents

* Funciones continuas

** Continuidad

*** Continuidad en un punto 				       :B_definition:
    :PROPERTIES:
    :BEAMER_env: definition
    :END:
    Sean \(A\subseteq \mathbb{C}\), \(a\in A\) y \(f\colon A\to
    \mathbb{C}\) una función. Decimos que \(f\) es *continua en
    \(a\)* si y solo si para cada \(\epsilon>0\) existe
    \(\delta>0\) tal que:
    \begin{displaymath}
    f(A\cap D(a,\delta))\subseteq D(f(a),\epsilon).
    \end{displaymath}

*** 
    Decimos que \(f\colon A\to \mathbb{C}\) es *continua* si es continua
    en \(a\) para todo \(a\in A\).

*** 								  :B_theorem:
    :PROPERTIES:
    :BEAMER_env: theorem
    :END:
    Sean \(A\subseteq \mathbb{C}\), \(a\in A\) y \(f\colon A\to
    \mathbb{C}\) una función. Entonces \(f\) es continua en \(a\)
    si y solo si para toda sucesión \(z_{n}\) en \(A\) tal que
    \(z_{n}\to a\), se tiene que \(f(z_{n})\to f(a)\).

** 

*** 								  :B_theorem:
    :PROPERTIES:
    :BEAMER_env: theorem
    :END:
    Sean \(f,g\colon A\to \mathbb{C}\) funciones continuas en \(a\in
    A\). Entonces \(cf\), \(\Re f\), \(\Im f\), \(\overline{f}\),
    \(f+g\), \(fg\) son continuas en \(a\). En particular si \(f,g\) son
    continuas, entonces cada una de las funciones listadas son
    continuas.

*** 								  :B_theorem:
    :PROPERTIES:
    :BEAMER_env: theorem
    :END:
    Si \(g(a)\ne 0\), entonces \(\frac{f}{g}\) es continua en
    \(a\). Si \(g(a)\ne 0\) para todo \(a\in A\), entonces
    \(\frac{f}{g}\) es continua. 

** 

*** 								  :B_theorem:
    :PROPERTIES:
    :BEAMER_env: theorem
    :END:
    Sean \(f\colon A\to \mathbb{C}\), \(g\colon B\to \mathbb{C}\)
    funciones tales que \(f(A)\subseteq B\). Si \(f\) es continua en
    \(a\in A\) y \(g\) es continua en \(f(a)\), entonces \(g\circ f\)
    es continua en \(a\). En particular, si \(f\) y \(g\) son
    continuas, entonces \(g\circ f\) es continua.

*** 								  :B_theorem:
    :PROPERTIES:
    :BEAMER_env: theorem
    :END:
    Sea \(U\subseteq \mathbb{C}\) abierto. Una función \(f\colon U\to
    \mathbb{C}\) es continua si y solo si para todo abierto
    \(V\subseteq \mathbb{C}\) se tiene que el conjunto
    \begin{displaymath}
    f^{-1}(V)=\{z\in U\mid f(z)\in V\},
    \end{displaymath}
    es abierto.

* Límites

** Definición de límite

*** 
    Dados \(a\in \mathbb{C}\) y \(r>0\), denotaremos con
    \(D^{*}(a,r)\) al conjunto \(D(a,r)-\{a\}\).

*** Límite 						       :B_definition:
    :PROPERTIES:
    :BEAMER_env: definition
    :END:

    Sean \(f\colon A\to \mathbb{C}\) una función y \(a\in \mathbb{C}\)
    un punto de acumulación de \(A\). Decimos que \(c\in \mathbb{C}\)
    es *límite de \(f\) en \(a\)*, denotado \(\lim_{z\to a}f(z)=c\), si
    para todo \(\epsilon>0\) existe \(\delta>0\) tal que:
    \begin{displaymath}
    f(A\cap D^{*}(a,\delta))\subseteq D(c,\epsilon).
    \end{displaymath}

** Relación con continuidad

*** 								  :B_theorem:
    :PROPERTIES:
    :BEAMER_env: theorem
    :END:
    Sea \(a\in A\) tal que \(a\) es punto de acumulación de
    \(A\). Entonces \(f\colon A\to \mathbb{C}\) es continua en \(a\)
    si y solo si \(\lim_{z\to a}f(z)=f(a)\).

** 

*** 								  :B_theorem:
    :PROPERTIES:
    :BEAMER_env: theorem
    :END:
    Sea \(a\) punto de acumulación de \(A\in \mathbb{C}\). Entonces
    \(f\colon A\to \mathbb{C}\) tiene límite \(c\) en \(a\) si y solo
    si para toda sucesión \(z_{n}\) en \(A-\{a\}\) con límite \(a\) se
    tiene que \(f(z_{n})\) converge a \(c\).

*** 								  :B_theorem:
    :PROPERTIES:
    :BEAMER_env: theorem
    :END:
    Sea \(A\subseteq \mathbb{C}\) y \(a\) un punto de acumulación de
    \(A\). Sean \(f,g\colon A\to \mathbb{C}\) funciones tales que
    \(\lim_{z\to a}f(z)=l_{1}\) y \(\lim_{z\to
    a}g(z)=l_{2}\). Entonces \(cf\), \(\Re f\), \(\Im f\),
    \(\overline{f}\), \(f+g\), \(fg\) tienen todas límite cuando
    \(z\to a\), y su valor es \(cl_{1}\), \(\Re l_{1}\), \(\Im
    l_{1}\), \(\overline{l_{1}}\), \(l_{1}+l_{2}\) y \(l_{1}l_{2}\),
    respectivamente. Si \(l_{2}\ne 0\), entonces \(\lim_{z\to
    a}\frac{f}{g}\) existe y es igual a \(\frac{l_{1}}{l_{2}}\).
