#+title: Teoremas del módulo máximo y del mapeo abierto
#+author: 
#+date: 2015-04-06 9:00
   
#+setupfile: opciones.org

#+beamer: \setbeamertemplate{navigation symbols}{}
#+beamer: \setbeamertemplate{items}[circle]
#+beamer: \languagepath{spanish}

#+latex_header: \usepackage{tikz}
#+latex_header: \usepackage{tikz-cd}
#+latex_header: \usepackage{pgfplots}
#+latex_header: \usetikzlibrary{babel}

#+beamer: \tableofcontents

* Teorema del módulo máximo

** 

*** Módulo máximo						  :B_theorem:
    :PROPERTIES:
    :BEAMER_env: theorem
    :END:
    Sean \(D\) abierto y \(f\colon D\to \mathbb{C}\) analítica y no
    constante. Entonces, para cada \(z_{0}\in D\) y \(\delta>0\),
    existe \(z\in D(z_{0},\delta)\cap D\) tal que
    \(|f(z)|>|f(z_{0})|\).

** Demostración

   - Si no es cierto, existen \(z_{0}\in D\) y \(\delta>0\) tal que
     para todo \(z\in D(z_{0},\delta)\) se tiene que
     \(|f(z)|\leq |f(z_{0})|\).
   - Sea \(r<\delta\). Tenemos que
     \(f(z_{0})=\frac{1}{2\pi}\int_{0}^{2\pi}f(z_{0}+re^{i\theta})\,d\theta\),
     de donde se obtiene:
     \begin{displaymath}
     |f(z_{0})|\leq\frac{1}{2\pi}\int_{0}^{2\pi}|f(z_{0}+re^{i\theta})|\,d\theta.
     \end{displaymath}
   - Por lo que:
     \begin{displaymath}
     0 \leq\frac{1}{2\pi}\int_{0}^{2\pi} (|f(z_{0}+re^{i\theta})|-|f(z_{0})|)\,d\theta.
     \end{displaymath}
   - Pero por nuestra hipótesis, el integrando es \(\leq 0\), por lo
     que la integral es también \(\leq 0\), y por lo tanto, igual a
     cero. Como el integrando es continuo, se tiene
     \(|f(z_{0}+re^{i\theta})|=|f(z_{0})|\) para toda \(\theta\).
   
** Demostración (continuación)

   - Como \(r<\delta\) es arbitrario, hemos demostrado entonces que
     \(|f|\) es una función constante en \(D(z_{0},\delta)\). Pero una
     de las consecuencias de las ecuaciones de Cauchy-Riemman dice que
     entonces \(f\) es constante en el mismo disco.
   - Se deduce entonces que \(f\) coincide con una constante en el
     disco, por lo tanto es constante en todo su dominio \(D\), lo
     cual contradice nuestra hipótesis de que \(f\) no es constante.

** Un corolario

*** Corolario
    Si \(f\) es analítica y no constante en un disco \(D(a,\delta)\) y
    continua en el disco cerrado, entonces \(|f|\) alcanza su máximo
    en la frontera del disco.

** Teorema del módulo mínimo

*** Módulo mínimo 						  :B_theorem:
    :PROPERTIES:
    :BEAMER_env: theorem
    :END:
    Sean \(D\) abierto y \(f\colon D\to \mathbb{C}\) analítica y no
    constante. Entonces, para cada \(z_{0}\in D\) y \(\delta>0\),
    existe \(z\in D(z_{0},\delta)\cap D\) tal que
    \(|f(z)|<|f(z_{0})|\), a menos que \(|f(z_{0})|=0\).

*** Demostración

    Si \(|f|\) alcanzara un mínimo local en \(z_{0}\ne 0\), entonces
    \(g=\frac{1}{f}\) sería tal que \(|g|\) alcanza un máximo local en
    \(z_{0}\), lo cual contradice que \(f\) no es constante.


** Lema de Schwarz

*** 								  :B_theorem:
    :PROPERTIES:
    :BEAMER_env: theorem
    :END:
    - Sea \(f\) analítica para \(|z|<1\) tal que: \(|f(z)|\leq 1\) y
      \(f(0)=0\). Entonces se obtiene que \(|f(z)|\leq|z|\) para toda
      \(|z|<1\) y que \(|f'(0)|\leq 1\).
    - Si además se tiene que \(|f(z)|=|z|\) para algún \(z\ne 0\), o
      bien que \(|f'(0)|=1\), entonces \(f(z)=cz\) para algún \(c\)
      tal que \(|c|=1\).


* Teorema del mapeo abierto

** 

*** Mapeo abierto 						  :B_theorem:
    :PROPERTIES:
    :BEAMER_env: theorem
    :END:
    Si \(U\subseteq\Omega\) es abierto, y \(f\colon\Omega\to
    \mathbb{C}\) es analítica y no constante, entonces \(f(U)\subseteq
    \mathbb{C}\) es abierto. 

** 

*** Demostración

    - Veremos que si \(f\) no es constante, y es analítica en \(a\),
      la imagen de un disco centrado en \(a\) contiene un disco
      centrado en \(f(a)\). Sin perder generalidad, \(f(a)=0\).
    - Sea \(C\) una circunferencia centrada en \(a\) tal que \(f(z)\ne
      0\) para \(z\in C\). Sea \(\epsilon=\min_{z\in C}\frac{|f(z)|}{2}\).
    - Sean \(w\in D(0,\epsilon)\), \(z\in C\). Entonces:
      \begin{displaymath}
      |f(z)-w|\geq |f(z)|-|w|\geq 2\epsilon-\epsilon=\epsilon
      \end{displaymath}
      mientras que \(|f(a)-w|=|-w|<\epsilon\).
    - Por lo tanto, la función \(|f(z)-w|\) alcanza su mínimo dentro
      de \(C\). Por el teorema de módulo mínimo, existe \(z_{0}\)
      dentro de \(C\) tal que \(|f(z_{0})-w|=0\), es decir, \(f(z_{0})=w\).
